#! /bin/bash
# 
# 'whois domain-name'能否找到以下三个服务之一:
#  ripe.net, cw.net, radb.net
# 
# 脚本命名为'wh', 然后放到/usr/local/bin/目录下，
# 需要符号链接:
#
# ln -s /usr/local/bin/wh /usr/local/bin/wh-ripe
# ln -s /usr/local/bin/wh /usr/local/bin/wh-cw
# ln -s /usr/local/bin/wh /usr/local/bin/wh-radb
#
# 脚本根据文件名调用不同的服务

E_NOARGS=65

if [ -z "$1" ]
then
    echo "Usage: `basename $0` [domain-name] "
    exit $E_NOARGS
fi

case `basename $0` in
    "wh" ) whois $1@whois.ripe.net;;
    "wh-ripe" ) whois $1@whois.ripe.net;;
    "wh-radb" ) whois $1@whois.radb.net;;
    "wh-cw" ) whois $1@whois.cw.net;;
    * ) echo "Usage: `basename $0` [domain-name]";;
esac

exit $?
