set nocompatible              " required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()


" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" add all your plugins here (note older versions of Vundle
" used Bundle instead of Plugin)
Plugin 'tmhedberg/SimpylFold'
Plugin 'vim-scripts/indentpython.vim'
Plugin 'vim-syntastic/syntastic'
Plugin 'Yggdroot/indentLine'
Plugin 'majutsushi/tagbar',
Plugin 'scrooloose/nerdtree'
Plugin 'jistr/vim-nerdtree-tabs'
Plugin 'kien/ctrlp.vim'
Plugin 'tpope/vim-fugitive'
Plugin 'Valloric/YouCompleteMe'
Plugin 'jiangmiao/auto-pairs'
Plugin 'ervandew/supertab'

Plugin 'plasticboy/vim-markdown'
Plugin 'suan/vim-instant-markdown'

Plugin 'mattn/emmet-vim'
Plugin 'SirVer/ultisnips'
Plugin 'honza/vim-snippets'
Plugin 'fatih/vim-go'


Plugin 'vim-erlang/vim-erlang-omnicomplete'
Plugin 'vim-erlang/vim-erlang-runtime'


" self
syntax on
set nu
set ruler
set mouse=a
set showcmd
set showmatch
set ignorecase
set smartcase
set incsearch
set autowrite
set hidden
set encoding=utf-8

set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab 
set smartindent
set autoindent 
set cindent

set backspace=indent,eol,start
set foldenable
set splitbelow
set splitright
set foldmethod=indent
set foldlevel=99

highlight Comment ctermfg=red guifg=red
colorscheme  desert

set runtimepath^=/root/.vim/bundle/vim-erlang-omnicomplete
set runtimepath^=/root/.vim/bundle/vim-erlang-runtime

nnoremap <Space> za
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-R> <C-W><C-R>


au BufNewFile,BufRead *.py
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix

au BufNewFile,BufRead *.js
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2

au BufNewFile,BufRead *.html
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2

au BufNewFile,BufRead *.css
    \ set tabstop=2 |
    \ set softtabstop=2 |
    \ set shiftwidth=2

au BufNewFile,BufRead *.md
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4

au BufNewFile,BufRead *.sh
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix

au BufNewFile,BufRead *.go
    \ set tabstop=4 |
    \ set softtabstop=4 |
    \ set shiftwidth=4 |
    \ set textwidth=79 |
    \ set expandtab |
    \ set autoindent |
    \ set fileformat=unix


"insert title
func SetTitle()
call setline(1,"#! /usr/bin/env python3")
call append(1,"# -*-coding:utf-8 -*-")
call append(2,"# @Time    : ".strftime('%Y/%m/%d %T',localtime()))
call append(3,"# @Author  : che")
call append(4,"# @Email   : ch1huizong@gmail.com")
normal G
normal o
normal o
endfunc
autocmd bufnewfile *.py call SetTitle()


let python_highlight_all=1
let g:ycm_confirm_extra_conf = 0
let g:ycm_python_binary_path = 'python3'


let g:SimpylFold_docstring_preview=1
let g:ycm_autoclose_preview_window_after_completion=1
map <leader>g  :YcmCompleter GoToDefinitionElseDeclaration<CR>


"Tagbar
nmap <F8> :TagbarToggle<CR>
let g:tagbar_left = 1

"Emmet
let g:user_emmet_install_global = 0
autocmd FileType html,css EmmetInstall
let g:user_emmet_leader_key='<Tab>'

"NERDTree
map <C-n> :NERDTreeToggle<CR>
let NERDTreeIgnore=['\.pyc$', '\~$'] "ignore files in NERDTree
let NERDTreeWinPos='left'


"indentline
let g:indentLine_enabled = 1

"snips
let g:ycm_key_list_select_completion = ['<C-n>', '<Down>']
let g:ycm_key_list_previous_completion = ['<C-p>', '<Up>']
let g:SuperTabDefaultCompletionType = '<C-n>'

" better key bindings for UltiSnipsExpandTrigger
let g:UltiSnipsExpandTrigger = "<tab>"
let g:UltiSnipsJumpForwardTrigger = "<tab>"
let g:UltiSnipsJumpBackwardTrigger = "<s-tab>"
let g:UltiSnipsEditSplit="vertical"

"Markdown
let g:instant_markdown_autostart = 1

"go
let g:go_bin_path = "/usr/local/go/bin"
let g:go_def_mode = "gopls"


" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required
